export const GET_ALL_GAMES = 'GET_ALL_GAMES'
export const GET_GAME_BY_ID = 'GET_GAME_BY_ID'
export const GET_GAMES_BY_QUERY = 'GET_GAMES_BY_QUERY'
export const REDIRECT = 'REDIRECT'
export const CLEAR_STATE_NAVIGATION = 'CLEAR_STATE_NAVIGATION'
export const CLEAR_STATE_DETAIL = 'CLEAR_STATE_DETAIL'
// export const CLEAR_STATE_GAMES = 'CLEAR_STATE_GAMES'

export const GET_GENRES = 'GET_GENRES'
// export const GET_PLATFORMS = 'GET_PLATFORMS'

export const FILTER_BY_GENRE = 'FILTER_BY_GENRE'
export const FILTER_BY_SOURCE = 'FILTER_BY_SOURCE'

export const SORT_BY = 'SORT_BY'
export const NAME_ASC = 'NAME_ASC'
export const NAME_DESC = 'NAME_DESC'
export const RATING_ASC = 'RATING_ASC'
export const RATING_DESC = 'RATING_DESC'

